#!/bin/bash

#  First time in .openshift/lib/utils might not exist, so add a check
#  to ensure file exists.
if [ -f "$OPENSHIFT_REPO_DIR/.openshift/lib/utils" ]; then
   #  Source utility functions.
   source "$OPENSHIFT_REPO_DIR/.openshift/lib/utils"

   #  Setup path to include the custom Node[.js] version.
   ver=$(get_node_version)
   echo ""
   echo "  - pre_stop_nodejs: Adding Node.js version $ver binaries to path"
   _SHOW_SETUP_PATH_MESSAGES="true" setup_path_for_custom_node_version
fi

